### ISSUE TITLE
Determine address prefixes

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/tesseract-core#1]
We need new prefixes for:
* legacy addresses
    * mainnet
    * testnet
    * regtest
* bech32 addresses
    * mainnet
    * testnet
    * regtest

**Comment by macterra** [comment]
As it stands Tesseract inherited:
* EQa and EQs for pubkey and script legacy addresses for mainnet from Equibit
* TQa and TQs for pubkey and script legacy addresses for testnet and regtest from Equibit
* ocn for mainnet bech32 from OCEAN
* ocntest for testnet bech32 from OCEAN
* ocnregtest for regtest bech32 from OCEAN

**Comment by Flaxscrip** [comment]
How about these: 

- TCa TCs (Tesseract-Core)
- TTa TTs (Tesseract Test)
- tct for mainnet bech32
- tsttest for testnet
- tstreg for regtest

**Comment by macterra** [comment]
Why tct for mainnet and tst for the other two bech32 prefixes?

**Comment by macterra** [comment]
FTR in the most recent commit the bech32 prefixes were changed to `tesr`, `tntesr`, and `rttesr`. I made the start of each one different to make it more obvious but I don't have a strong preference. I do strongly prefer `tesr` or `tsr` over `tst` because the latter always reminds me of "test", not tesseract.

**Comment by macterra** [comment]
We should also probably avoid include "Core" in the acronym unless you want to rule out other implementations of Tesseract a priori. (Bitcoin core is just the reference implementation)

**Comment by macterra** [comment]
I suggest
* TSa TSs (Tesseract main)
* TTa TTs (Tesseract Test)
* tsr for mainnet bech32
* tsrtest for testnet
* tsrregt for regtest

**Comment by Flaxscrip** [comment]
I like the final suggestion here, except maybe for the TSA (lol). Thank you for thinking this through.

**Comment by macterra** [comment]
I don't think the TSa address will see much use but there is still time to change it...

**Comment by Flaxscrip** [comment]
Everyone will be using bech32. Let's leave it as suggested.

**Comment by Flaxscrip** [comment]
We need our wiki to reflect the updated bech32 Tesseract-Core prefies which changed recently: 
https://github.com/cryptotechguru/tesseract-core/issues/1#event-2318655780
